#!/bin/bash

main() {
  readonly PROJECT_NAME="test_project"
  readonly SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
  readonly ROOT_DIR="$(pwd && cd ../)"

  if ! [[ -f "$ROOT_DIR/.env" ]]; then
    echo "[FAIL] env file not found."
    exit 1
  fi

  # read env
  readonly GIT_REPO=''
  readonly GIT_TOKEN=''

  echo "[INFO] You are trying to close all PRs on ${GIT_REPO}."
  read -p "? Continue (y/n) " -n 1
  printf "\n"

  # Get all opend PRs
  # https://developer.github.com/v3/pulls/#list-pull-requests
  # http://www.starkandwayne.com/blog/bash-for-loop-over-json-array-using-jq/
  prs="$(curl -s "https://api.github.com/repos/${GIT_REPO}/pulls")"
  for row in $(echo "${prs}" | jq -r '.[] | @base64'); do
    _jq() {
     echo ${row} | base64 --decode | jq -r ${1}
    }

    number=$(_jq '.number')
    url="https://api.github.com/repos/${GIT_REPO}/pulls/${number}"

    # Close the PR
    # https://developer.github.com/v3/pulls/#update-a-pull-request
    echo "[INFO] closing ${url}"
    curl -s -X PATCH -H "Authorization: Bearer ${GIT_TOKEN}" -H "Content-Type: application/json" "${url}" -d '{"state":"closed"}'
    if ! [[ 0 -eq $? ]]; then
      echo "[FAIL] Unfortunately, fail to close a PR#${number}"
      exit 1
    fi
  done
}

main "$@"
